name: Dev builds

on:
  push:
    branches:
      - main
      - 'release-v[0-9]+.[0-9]+'

env:
  SIDECAR_IMAGE: "ghcr.io/sumologic/tailing-sidecar"
  OPERATOR_IMAGE: "ghcr.io/sumologic/tailing-sidecar-operator"
  LATEST_TAG: "main"

jobs:
  build-sidecar:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - name: Extract tag
        id: extract_tag
        run: echo "::set-output name=tag::$(echo $(git describe --tags --always))"
      - name: Print container tag
        run: echo "Running dev build for ${{ steps.extract_tag.outputs.tag }}"

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2.1.0

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2.2.1
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2.1.0
        with:
          registry: ghcr.io
          username: USERNAME
          password: ${{ secrets.CR_PAT }}
      - name: Build and push tailing sidecar multiplatform image
        run: make build-push-multiplatform IMG=${{ env.SIDECAR_IMAGE }}:${{ steps.extract_tag.outputs.tag }}
        working-directory: ./sidecar
      - name: Set latest image for tailing sidecar
        run: docker tag ${{ env.SIDECAR_IMAGE }}:${{ steps.extract_tag.outputs.tag }} ${{ env.SIDECAR_IMAGE }}:${{ env.LATEST_TAG }}
      - name: Push tailing sidecar image with latest tag
        run: make push TAG=${{ env.SIDECAR_IMAGE }}:${{ env.LATEST_TAG }}

  build-operator:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - name: Setup go
        uses: actions/setup-go@v3
        with:
          go-version: '1.18'
      - name: Extract tag
        id: extract_tag
        run: echo "::set-output name=tag::$(echo $(git describe --tags --always))"
      - name: Print container tag
        run: echo "Running dev build for ${{ steps.extract_tag.outputs.tag }}"

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2.1.0

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2.2.1
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2.1.0
        with:
          registry: ghcr.io
          username: USERNAME
          password: ${{ secrets.CR_PAT }}
      - name: Build and push tailing sidecar operator multiplatform image
        run: make build-push-multiplatform IMG=${{ env.OPERATOR_IMAGE }}:${{ steps.extract_tag.outputs.tag }}
        working-directory: ./operator
      - name: Set latest image for tailing sidecar operator
        run: docker tag ${{ env.OPERATOR_IMAGE }}:${{ steps.extract_tag.outputs.tag }} ${{ env.OPERATOR_IMAGE }}:${{ env.LATEST_TAG }}	
      - name: Push tailing sidecar operator image with latest tag
        run: make docker-push IMG=${{ env.OPERATOR_IMAGE }}:${{ env.LATEST_TAG }}

  push-helm-chart:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - name: Push dev helm chart
        run: make push-helm-chart
