name: Releases

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'
env:
  SIDECAR_IMAGE: "ghcr.io/sumologic/tailing-sidecar"
  OPERATOR_IMAGE: "ghcr.io/sumologic/tailing-sidecar-operator"
  LATEST_TAG: "latest"

jobs:
  build-sidecar:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Extract tag
        id: extract_tag
        run: echo "::set-output name=tag::$(echo ${GITHUB_REF#refs/tags/v})"
      - name: Print container tag
        run: echo "Running release build for ${{ steps.extract_tag.outputs.tag }}"
      - name: Build tailing sidecar image
        run: make build TAG=${{ env.SIDECAR_IMAGE }}:${{ steps.extract_tag.outputs.tag }}
        working-directory: ./sidecar
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1.9.0
        with:
          registry: ghcr.io
          username: USERNAME
          password: ${{ secrets.CR_PAT }}
      - name: Push tailing sidecar image
        run: make push TAG=${{ env.SIDECAR_IMAGE }}:${{ steps.extract_tag.outputs.tag }}
        working-directory: ./sidecar
      - name: Set latest image for tailing sidecar
        run: docker tag ${{ env.SIDECAR_IMAGE }}:${{ steps.extract_tag.outputs.tag }} ${{ env.SIDECAR_IMAGE }}:${{ env.LATEST_TAG }}
      - name: Push tailing sidecar image with latest tag
        run: make push TAG=${{ env.SIDECAR_IMAGE }}:${{ env.LATEST_TAG }}
        working-directory: ./sidecar

  build-operator:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Extract tag
        id: extract_tag
        run: echo "::set-output name=tag::$(echo ${GITHUB_REF#refs/tags/v})"
      - name: Print container tag
        run: echo "Running release build for ${{ steps.extract_tag.outputs.tag }}"
      - name: Build tailing sidecar operator image
        run: make docker-build IMG=${{ env.OPERATOR_IMAGE }}:${{ steps.extract_tag.outputs.tag }}
        working-directory: ./operator
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1.9.0
        with:
          registry: ghcr.io
          username: USERNAME
          password: ${{ secrets.CR_PAT }}
      - name: Push tailing sidecar operator image
        run: make docker-push IMG=${{ env.OPERATOR_IMAGE }}:${{ steps.extract_tag.outputs.tag }}
        working-directory: ./operator
      - name: Set latest image for tailing sidecar operator
        run: docker tag ${{ env.OPERATOR_IMAGE }}:${{ steps.extract_tag.outputs.tag }} ${{ env.OPERATOR_IMAGE }}:${{ env.LATEST_TAG }}
      - name: Push tailing sidecar operator image with latest tag
        run: make docker-push IMG=${{ env.OPERATOR_IMAGE }}:${{ env.LATEST_TAG }}
        working-directory: ./operator

  push-helm-chart:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Push dev helm chart
        run: make push-helm-chart
